#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sangam Literature Work Metadata
Centralized metadata for all 18 Sangam works (Collection 51)

Sangam literature represents the earliest Tamil classical poetry,
divided into two major categories:
- எட்டுத்தொகை (Ettuthokai - Eight Anthologies) - thogai type
- பத்துப்பாட்டு (Pathupaattu - Ten Idylls) - padal type
"""

# Collection-level constants
COLLECTION_ID = 51
COLLECTION_NAME = 'Sangam Literature'
COLLECTION_NAME_TAMIL = 'சங்க இலக்கியம்'
COLLECTION_DESCRIPTION = 'Classical Tamil poetry from the Sangam period (100 BCE - 250 CE) - 18 works on love, war, ethics, and nature'

WORK_METADATA = {
    '1 நற்றிணை.txt': {
        'work_name': 'Natrrinai',
        'work_name_tamil': 'நற்றிணை',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100 BCE - 100 CE',
        'description': 'Collection of 400 poems from the Sangam period, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': -100,
        'chronology_end_year': 100,
        'chronology_confidence': 'high',
        'chronology_notes': 'Considered among the earliest Sangam works',
        'canonical_order': 202,
        'position_in_collection': 2,
        'type': 'thogai',
        'traditional_order': 2
    },
    '2 குறுந்தொகை.txt': {
        'work_name': 'Kurunthokai',
        'work_name_tamil': 'குறுந்தொகை',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100 BCE - 100 CE',
        'description': 'Short poems on love and war from the Sangam period, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': -100,
        'chronology_end_year': 100,
        'chronology_confidence': 'high',
        'chronology_notes': 'Early Sangam anthology',
        'canonical_order': 203,
        'position_in_collection': 3,
        'type': 'thogai',
        'traditional_order': 3
    },
    '3 ஐங்குறுநூறு.txt': {
        'work_name': 'Ainkurunuru',
        'work_name_tamil': 'ஐங்குறுநூறு',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100 BCE - 200 CE',
        'description': 'Five hundred short poems from the Sangam period, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': -100,
        'chronology_end_year': 200,
        'chronology_confidence': 'high',
        'chronology_notes': 'Sangam anthology of 500 short love poems',
        'canonical_order': 204,
        'position_in_collection': 4,
        'type': 'thogai',
        'traditional_order': 4
    },
    '4 பதிற்றுப்பத்து.txt': {
        'work_name': 'Pathitrupathu',
        'work_name_tamil': 'பதிற்றுப்பத்து',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100-200 CE',
        'description': 'Ten tens of poems featuring Chera kings, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': 100,
        'chronology_end_year': 200,
        'chronology_confidence': 'high',
        'chronology_notes': 'Features Chera kings, slightly later than other anthologies',
        'canonical_order': 205,
        'position_in_collection': 5,
        'type': 'thogai',
        'traditional_order': 5
    },
    '5 பரிபாடல்.txt': {
        'work_name': 'Paripaadal',
        'work_name_tamil': 'பரிபாடல்',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100-200 CE',
        'description': 'Songs in Paripadal meter - religious hymns to Murugan and Thirumal, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': 100,
        'chronology_end_year': 200,
        'chronology_confidence': 'high',
        'chronology_notes': 'Religious hymns to Murugan and Thirumal',
        'canonical_order': 206,
        'position_in_collection': 6,
        'type': 'thogai',
        'traditional_order': 6
    },
    '6 கலித்தொகை.txt': {
        'work_name': 'Kalithokai',
        'work_name_tamil': 'கலித்தொகை',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100-250 CE',
        'description': 'Collection of Kali meter poems from the Sangam period, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': 100,
        'chronology_end_year': 250,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Some scholars date to later Sangam period',
        'canonical_order': 207,
        'position_in_collection': 7,
        'type': 'thogai',
        'traditional_order': 7
    },
    '7 அகநானூறு.txt': {
        'work_name': 'Aganaanuru',
        'work_name_tamil': 'அகநானூறு',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100 BCE - 200 CE',
        'description': 'Four hundred poems on love from the Sangam period, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': -100,
        'chronology_end_year': 200,
        'chronology_confidence': 'high',
        'chronology_notes': '400 love poems from Sangam period',
        'canonical_order': 208,
        'position_in_collection': 8,
        'type': 'thogai',
        'traditional_order': 8
    },
    '8 புறநானூறு.txt': {
        'work_name': 'Puranaanuru',
        'work_name_tamil': 'புறநானூறு',
        'author': 'Multiple poets',
        'author_tamil': 'பல புலவர்கள்',
        'period': '100 BCE - 200 CE',
        'description': 'Four hundred poems on war and ethics from the Sangam period, part of Ettuthokai (Eight Anthologies)',
        'chronology_start_year': -100,
        'chronology_end_year': 200,
        'chronology_confidence': 'high',
        'chronology_notes': 'Historical references help date some poems precisely',
        'canonical_order': 209,
        'position_in_collection': 9,
        'type': 'thogai',
        'traditional_order': 9
    },
    '9 திருமுருகாற்றுப்படை.txt': {
        'work_name': 'Thirumurugaatruppadai',
        'work_name_tamil': 'திருமுருகாற்றுப்படை',
        'author': 'Nakkirar',
        'author_tamil': 'நக்கீரர்',
        'period': '150-250 CE',
        'description': 'Guide to Lord Murugan - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 210,
        'position_in_collection': 10,
        'type': 'padal',
        'traditional_order': 10
    },
    '10 பொருநராற்றுப்படை.txt': {
        'work_name': 'Porunaraatruppadai',
        'work_name_tamil': 'பொருநராற்றுப்படை',
        'author': 'Muthathamakkanniyaar',
        'author_tamil': 'முதத்தமக்கண்ணியார்',
        'period': '150-250 CE',
        'description': 'Guide to patron - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 211,
        'position_in_collection': 11,
        'type': 'padal',
        'traditional_order': 11
    },
    '11 சிறுபாணாற்றுப்படை.txt': {
        'work_name': 'Sirupanaatruppadai',
        'work_name_tamil': 'சிறுபாணாற்றுப்படை',
        'author': 'Nattattanaar',
        'author_tamil': 'நத்தத்தனார்',
        'period': '150-250 CE',
        'description': 'Guide to small drum player - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 212,
        'position_in_collection': 12,
        'type': 'padal',
        'traditional_order': 12
    },
    '12 பெரும்பாணாற்றுப்படை.txt': {
        'work_name': 'Perumpanaatruppadai',
        'work_name_tamil': 'பெரும்பாணாற்றுப்படை',
        'author': 'Uruttirankaannanaaar',
        'author_tamil': 'உருத்திரங்கண்ணனார்',
        'period': '150-250 CE',
        'description': 'Guide to great drum player - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 213,
        'position_in_collection': 13,
        'type': 'padal',
        'traditional_order': 13
    },
    '13 முல்லைப்பாட்டு.txt': {
        'work_name': 'Mullaippaattu',
        'work_name_tamil': 'முல்லைப்பாட்டு',
        'author': 'Nappoothanaaar',
        'author_tamil': 'நப்பூதனார்',
        'period': '150-250 CE',
        'description': 'Song of Mullai landscape - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 214,
        'position_in_collection': 14,
        'type': 'padal',
        'traditional_order': 14
    },
    '14 மதுரைக்காஞ்சி.txt': {
        'work_name': 'Madurai kanchi',
        'work_name_tamil': 'மதுரைக்காஞ்சி',
        'author': 'Maangudi Marudhanaar',
        'author_tamil': 'மாங்குடி மருதனார்',
        'period': '150-250 CE',
        'description': 'Description of Madurai city - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 215,
        'position_in_collection': 15,
        'type': 'padal',
        'traditional_order': 15
    },
    '15 நெடுநல்வாடை.txt': {
        'work_name': 'Nedunalvaadai',
        'work_name_tamil': 'நெடுநல்வாடை',
        'author': 'Nakkirar',
        'author_tamil': 'நக்கீரர்',
        'period': '150-250 CE',
        'description': 'The long north wind - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 216,
        'position_in_collection': 16,
        'type': 'padal',
        'traditional_order': 16
    },
    '16 குறிஞ்சிப்பாட்டு.txt': {
        'work_name': 'Kurinchippaattu',
        'work_name_tamil': 'குறிஞ்சிப்பாட்டு',
        'author': 'Kapilar',
        'author_tamil': 'கபிலர்',
        'period': '150-250 CE',
        'description': 'Song of Kurinji landscape - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 217,
        'position_in_collection': 17,
        'type': 'padal',
        'traditional_order': 17
    },
    '17 பட்டினப்பாலை.txt': {
        'work_name': 'Pattinappaalai',
        'work_name_tamil': 'பட்டினப்பாலை',
        'author': 'Uruttirankaannanaaar',
        'author_tamil': 'உருத்திரங்கண்ணனார்',
        'period': '150-250 CE',
        'description': 'Description of seaport - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 218,
        'position_in_collection': 18,
        'type': 'padal',
        'traditional_order': 18
    },
    '18 மலைபடுகடாம்.txt': {
        'work_name': 'Malaipadukataam',
        'work_name_tamil': 'மலைபடுகடாம்',
        'author': 'Perunkadungo',
        'author_tamil': 'பெருங்கடுங்கோ',
        'period': '150-250 CE',
        'description': 'Mountain-traversing journey - part of Pathupaattu (Ten Idylls)',
        'chronology_start_year': 150,
        'chronology_end_year': 250,
        'chronology_confidence': 'high',
        'chronology_notes': 'Part of Pathupaattu (Ten Idylls)',
        'canonical_order': 219,
        'position_in_collection': 19,
        'type': 'padal',
        'traditional_order': 19
    }
}
