#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Thirumurai Collection Metadata
===============================

Collection: Thirumurai (திருமுறை) - Collection ID: 321
12 Thirumurai subcollections (321.1 - 321.12) under Devotional Literature (323)
60 works total spanning 6th-12th century CE

Structure:
- Files 1-7: Devaram (தேவாரம்) - 7 works by 3 Nayanmars
- File 8.1: Thiruvasagam (1 work)
- File 8.2: Thirukkovayar (1 work)
- File 9: Thiruvisaippa + Thiruppallandu (10 works)
- File 10: Thirumanthiram (1 work)
- File 11: Saiva Prabandha Malai (39 works)
- File 12: Periya Puranam (1 work)

Import Script: thirumurai_bulk_import.py
Delete Script: delete_thirumurai.py
"""

COLLECTION_ID = 321
COLLECTION_NAME = 'Thirumurai'
COLLECTION_NAME_TAMIL = 'திருமுறை'

# 12 Thirumurai subcollections (under Devotional Literature 323)
SUBCOLLECTIONS = {
    1: {'id': 3211, 'name': 'முதலாம் திருமுறை', 'name_en': 'Thirumurai 1'},
    2: {'id': 3212, 'name': 'இரண்டாம் திருமுறை', 'name_en': 'Thirumurai 2'},
    3: {'id': 3213, 'name': 'மூன்றாம் திருமுறை', 'name_en': 'Thirumurai 3'},
    4: {'id': 3214, 'name': 'நான்காம் திருமுறை', 'name_en': 'Thirumurai 4'},
    5: {'id': 3215, 'name': 'ஐந்தாம் திருமுறை', 'name_en': 'Thirumurai 5'},
    6: {'id': 3216, 'name': 'ஆறாம் திருமுறை', 'name_en': 'Thirumurai 6'},
    7: {'id': 3217, 'name': 'ஏழாம் திருமுறை', 'name_en': 'Thirumurai 7'},
    8: {'id': 3218, 'name': 'எட்டாம் திருமுறை', 'name_en': 'Thirumurai 8'},
    9: {'id': 3219, 'name': 'ஒன்பதாம் திருமுறை', 'name_en': 'Thirumurai 9'},
    10: {'id': 32110, 'name': 'பத்தாம் திருமுறை', 'name_en': 'Thirumurai 10'},
    11: {'id': 32111, 'name': 'பதினொன்றாம் திருமுறை', 'name_en': 'Thirumurai 11'},
    12: {'id': 32112, 'name': 'பன்னிரண்டாம் திருமுறை', 'name_en': 'Thirumurai 12'},
}

WORK_METADATA = {
    'devaram_1': {
        'work_name': 'Devaram - Thirumurai 1',
        'work_name_tamil': 'தேவாரம் - முதலாம் திருமுறை',
        'author': 'Thirugnanasambandar',
        'author_tamil': 'திருஞானசம்பந்தர்',
        'chronology_start_year': 600,
        'chronology_end_year': 650,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Thirugnanasambandar from 7th-8th century CE',
        'canonical_order': 321001,
        'position_in_collection': 1,
        'file': '1.முதலாம் திருமுறை.txt',
        'subcollection_id': 3211
    },
    'devaram_2': {
        'work_name': 'Devaram - Thirumurai 2',
        'work_name_tamil': 'தேவாரம் - இரண்டாம் திருமுறை',
        'author': 'Thirugnanasambandar',
        'author_tamil': 'திருஞானசம்பந்தர்',
        'chronology_start_year': 600,
        'chronology_end_year': 650,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Thirugnanasambandar from 7th-8th century CE',
        'canonical_order': 321002,
        'position_in_collection': 2,
        'file': '2.இரண்டாம் திருமுறை.txt',
        'subcollection_id': 3212
    },
    'devaram_3': {
        'work_name': 'Devaram - Thirumurai 3',
        'work_name_tamil': 'தேவாரம் - மூன்றாம் திருமுறை',
        'author': 'Thirugnanasambandar',
        'author_tamil': 'திருஞானசம்பந்தர்',
        'chronology_start_year': 600,
        'chronology_end_year': 650,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Thirugnanasambandar from 7th-8th century CE',
        'canonical_order': 321003,
        'position_in_collection': 3,
        'file': '3.மூன்றாம் திருமுறை.txt',
        'subcollection_id': 3213
    },
    'devaram_4': {
        'work_name': 'Devaram - Thirumurai 4',
        'work_name_tamil': 'தேவாரம் - நான்காம் திருமுறை',
        'author': 'Thirunavukkarasar (Appar)',
        'author_tamil': 'திருநாவுக்கரசர்',
        'chronology_start_year': 600,
        'chronology_end_year': 650,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Thirunavukkarasar (Appar) from 7th-8th century CE',
        'canonical_order': 321004,
        'position_in_collection': 4,
        'file': '4.நான்காம்_திருமுறை.txt',
        'subcollection_id': 3214
    },
    'devaram_5': {
        'work_name': 'Devaram - Thirumurai 5',
        'work_name_tamil': 'தேவாரம் - ஐந்தாம் திருமுறை',
        'author': 'Thirunavukkarasar (Appar)',
        'author_tamil': 'திருநாவுக்கரசர்',
        'chronology_start_year': 600,
        'chronology_end_year': 650,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Thirunavukkarasar (Appar) from 7th-8th century CE',
        'canonical_order': 321005,
        'position_in_collection': 5,
        'file': '5.ஐந்தாம் திருமுறை.txt',
        'subcollection_id': 3215
    },
    'devaram_6': {
        'work_name': 'Devaram - Thirumurai 6',
        'work_name_tamil': 'தேவாரம் - ஆறாம் திருமுறை',
        'author': 'Thirunavukkarasar (Appar)',
        'author_tamil': 'திருநாவுக்கரசர்',
        'chronology_start_year': 600,
        'chronology_end_year': 650,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Thirunavukkarasar (Appar) from 7th-8th century CE',
        'canonical_order': 321006,
        'position_in_collection': 6,
        'file': '6.ஆறாம் திருமுறை.txt',
        'subcollection_id': 3216
    },
    'devaram_7': {
        'work_name': 'Devaram - Thirumurai 7',
        'work_name_tamil': 'தேவாரம் - ஏழாம் திருமுறை',
        'author': 'Sundarar',
        'author_tamil': 'சுந்தரர்',
        'chronology_start_year': 700,
        'chronology_end_year': 750,
        'chronology_confidence': 'high',
        'chronology_notes': 'Devaram hymns by Sundarar from 7th-8th century CE',
        'canonical_order': 321007,
        'position_in_collection': 7,
        'file': '7.ஏழாம் திருமுறை.txt',
        'subcollection_id': 3217
    },
    'thiruvasagam': {
        'work_name': 'Thiruvasagam',
        'work_name_tamil': 'திருவாசகம்',
        'author': 'Manikkavasagar',
        'author_tamil': 'மாணிக்கவாசகர்',
        'chronology_start_year': 800,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Composed by Manikkavasagar in 9th century CE',
        'canonical_order': 321008,
        'position_in_collection': 8,
        'file': '8.1எட்டாம் திருமுறை.txt',
        'subcollection_id': 3218
    },
    'thirukkovayar': {
        'work_name': 'Thirukkovayar',
        'work_name_tamil': 'திருக்கோவையார்',
        'author': 'Manikkavasagar',
        'author_tamil': 'மாணிக்கவாசகர்',
        'chronology_start_year': 800,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Composed by Manikkavasagar in 9th century CE',
        'canonical_order': 321009,
        'position_in_collection': 9,
        'file': '8.2 எட்டாம் திருமுறை.txt',
        'subcollection_id': 3218
    },
    'file9_1': {
        'work_name': 'திருமாளிகைத் தேவர் பதிகங்கள்',
        'work_name_tamil': 'திருமாளிகைத் தேவர் பதிகங்கள்',
        'author': 'திருமாளிகைத் தேவர்',
        'author_tamil': 'திருமாளிகைத் தேவர்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321010,
        'position_in_collection': 10,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_2': {
        'work_name': 'சேந்தனார் பதிகங்கள்',
        'work_name_tamil': 'சேந்தனார் பதிகங்கள்',
        'author': 'சேந்தனார்',
        'author_tamil': 'சேந்தனார்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321011,
        'position_in_collection': 11,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_3': {
        'work_name': 'கருவூர்த் தேவர் பதிகங்கள்',
        'work_name_tamil': 'கருவூர்த் தேவர் பதிகங்கள்',
        'author': 'கருவூர்த் தேவர்',
        'author_tamil': 'கருவூர்த் தேவர்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321012,
        'position_in_collection': 12,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_4': {
        'work_name': 'பூந்துருத்தி நம்பி காடநம்பி பதிகங்கள்',
        'work_name_tamil': 'பூந்துருத்தி நம்பி காடநம்பி பதிகங்கள்',
        'author': 'பூந்துருத்தி நம்பி காடநம்பி',
        'author_tamil': 'பூந்துருத்தி நம்பி காடநம்பி',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321013,
        'position_in_collection': 13,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_5': {
        'work_name': 'கண்டராதித்தர் பதிகங்கள்',
        'work_name_tamil': 'கண்டராதித்தர் பதிகங்கள்',
        'author': 'கண்டராதித்தர்',
        'author_tamil': 'கண்டராதித்தர்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321014,
        'position_in_collection': 14,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_6': {
        'work_name': 'வேணாட்டடிகள் பதிகங்கள்',
        'work_name_tamil': 'வேணாட்டடிகள் பதிகங்கள்',
        'author': 'வேணாட்டடிகள்',
        'author_tamil': 'வேணாட்டடிகள்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321015,
        'position_in_collection': 15,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_7': {
        'work_name': 'திருவாலியமுதனார் பதிகங்கள்',
        'work_name_tamil': 'திருவாலியமுதனார் பதிகங்கள்',
        'author': 'திருவாலியமுதனார்',
        'author_tamil': 'திருவாலியமுதனார்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321016,
        'position_in_collection': 16,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_8': {
        'work_name': 'புருடோத்தம நம்பி பதிகங்கள்',
        'work_name_tamil': 'புருடோத்தம நம்பி பதிகங்கள்',
        'author': 'புருடோத்தம நம்பி',
        'author_tamil': 'புருடோத்தம நம்பி',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321017,
        'position_in_collection': 17,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_9': {
        'work_name': 'சேதிராயர் பதிகங்கள்',
        'work_name_tamil': 'சேதிராயர் பதிகங்கள்',
        'author': 'சேதிராயர்',
        'author_tamil': 'சேதிராயர்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321018,
        'position_in_collection': 18,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'file9_10': {
        'work_name': 'Thiruppallandu',
        'work_name_tamil': 'திருப்பல்லாண்டு',
        'author': 'சேந்தனார்',
        'author_tamil': 'சேந்தனார்',
        'chronology_start_year': 700,
        'chronology_end_year': 900,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Part of Thiruvisaippa collection, 7th-9th century CE',
        'canonical_order': 321019,
        'position_in_collection': 19,
        'file': '9.ஒன்பதாம் திருமுறை.txt',
        'subcollection_id': 3219
    },
    'thirumanthiram': {
        'work_name': 'Thirumanthiram',
        'work_name_tamil': 'திருமந்திரம்',
        'author': 'Thirumoolar',
        'author_tamil': 'திருமூலர்',
        'chronology_start_year': 200,
        'chronology_end_year': 600,
        'chronology_confidence': 'low',
        'chronology_notes': 'Dating disputed - estimates range from 2nd to 6th century CE',
        'canonical_order': 321020,
        'position_in_collection': 20,
        'file': '10.பத்தாம் திருமுறை.txt',
        'subcollection_id': 32110
    },
    'file11_1': {
        'work_name': 'திருமுகப்பாசுரம்',
        'work_name_tamil': 'திருமுகப்பாசுரம்',
        'author': 'திருஆலவாய் உடையார்',
        'author_tamil': 'திருஆலவாய் உடையார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321021,
        'position_in_collection': 21,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_2': {
        'work_name': 'மூத்த திருப்பதிகம்',
        'work_name_tamil': 'மூத்த திருப்பதிகம்',
        'author': 'காரைக்கால் அம்மையார்',
        'author_tamil': 'காரைக்கால் அம்மையார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321022,
        'position_in_collection': 22,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_3': {
        'work_name': 'திருஇரட்டைமணிமாலை',
        'work_name_tamil': 'திருஇரட்டைமணிமாலை',
        'author': 'காரைக்கால் அம்மையார்',
        'author_tamil': 'காரைக்கால் அம்மையார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321023,
        'position_in_collection': 23,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_4': {
        'work_name': 'அற்புதத் திருவந்தாதி',
        'work_name_tamil': 'அற்புதத் திருவந்தாதி',
        'author': 'காரைக்கால் அம்மையார்',
        'author_tamil': 'காரைக்கால் அம்மையார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321024,
        'position_in_collection': 24,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_5': {
        'work_name': 'சேத்திரத் திருவெண்பா',
        'work_name_tamil': 'சேத்திரத் திருவெண்பா',
        'author': 'ஐயடிகள் காடவர் கோன் நாயனார்',
        'author_tamil': 'ஐயடிகள் காடவர் கோன் நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321025,
        'position_in_collection': 25,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_6': {
        'work_name': 'பொன்வண்ணத்து அந்தாதி',
        'work_name_tamil': 'பொன்வண்ணத்து அந்தாதி',
        'author': 'சேரமான் பெருமாள் நாயனார்',
        'author_tamil': 'சேரமான் பெருமாள் நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321026,
        'position_in_collection': 26,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_7': {
        'work_name': 'திருவாரூர் மும்மணிக்கோவை',
        'work_name_tamil': 'திருவாரூர் மும்மணிக்கோவை',
        'author': 'சேரமான் பெருமாள் நாயனார்',
        'author_tamil': 'சேரமான் பெருமாள் நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321027,
        'position_in_collection': 27,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_8': {
        'work_name': 'திருக்கைலாய ஞானஉலா (ஆதி உலா)',
        'work_name_tamil': 'திருக்கைலாய ஞானஉலா (ஆதி உலா)',
        'author': 'சேரமான் பெருமாள்',
        'author_tamil': 'சேரமான் பெருமாள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321028,
        'position_in_collection': 28,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_9': {
        'work_name': 'கயிலைபாதி காளத்திபாதி அந்தாதி',
        'work_name_tamil': 'கயிலைபாதி காளத்திபாதி அந்தாதி',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321029,
        'position_in_collection': 29,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_10': {
        'work_name': 'திருஈங்கோய்மலை எழுபது',
        'work_name_tamil': 'திருஈங்கோய்மலை எழுபது',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321030,
        'position_in_collection': 30,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_11': {
        'work_name': 'திருவலஞ்சுழி மும்மணிக்கோவை',
        'work_name_tamil': 'திருவலஞ்சுழி மும்மணிக்கோவை',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321031,
        'position_in_collection': 31,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_12': {
        'work_name': 'திருஎழுகூற்றிருக்கை',
        'work_name_tamil': 'திருஎழுகூற்றிருக்கை',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321032,
        'position_in_collection': 32,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_13': {
        'work_name': 'பெருந்தேவபாணி',
        'work_name_tamil': 'பெருந்தேவபாணி',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321033,
        'position_in_collection': 33,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_14': {
        'work_name': 'கோபப் பிரசாதம்',
        'work_name_tamil': 'கோபப் பிரசாதம்',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321034,
        'position_in_collection': 34,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_15': {
        'work_name': 'கார் எட்டு',
        'work_name_tamil': 'கார் எட்டு',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321035,
        'position_in_collection': 35,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_16': {
        'work_name': 'போற்றித் திருக்கலிவெண்பா',
        'work_name_tamil': 'போற்றித் திருக்கலிவெண்பா',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321036,
        'position_in_collection': 36,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_18': {
        'work_name': 'திருக்கண்ணப்ப தேவர் திருமறம்',
        'work_name_tamil': 'திருக்கண்ணப்ப தேவர் திருமறம்',
        'author': 'நக்கீரதேவ நாயனார்',
        'author_tamil': 'நக்கீரதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321037,
        'position_in_collection': 37,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_19': {
        'work_name': 'திருக்கண்ணப்ப தேவர் திருமறம்',
        'work_name_tamil': 'திருக்கண்ணப்ப தேவர் திருமறம்',
        'author': 'கல்லாட தேவ நாயனார்',
        'author_tamil': 'கல்லாட தேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321038,
        'position_in_collection': 38,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_20': {
        'work_name': 'மூத்த நாயனார் திருஇரட்டை மணிமாலை',
        'work_name_tamil': 'மூத்த நாயனார் திருஇரட்டை மணிமாலை',
        'author': 'கபில தேவ நாயனார்',
        'author_tamil': 'கபில தேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321039,
        'position_in_collection': 39,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_21': {
        'work_name': 'சிவபெருமான் திருஇரட்டை மணிமாலை',
        'work_name_tamil': 'சிவபெருமான் திருஇரட்டை மணிமாலை',
        'author': 'கபில தேவ நாயனார்',
        'author_tamil': 'கபில தேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321040,
        'position_in_collection': 40,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_22': {
        'work_name': 'சிவபெருமான் திருவந்தாதி',
        'work_name_tamil': 'சிவபெருமான் திருவந்தாதி',
        'author': 'கபிலதேவ நாயனார்',
        'author_tamil': 'கபிலதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321041,
        'position_in_collection': 41,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_23': {
        'work_name': 'சிவபெருமான் திருஅந்தாதி',
        'work_name_tamil': 'சிவபெருமான் திருஅந்தாதி',
        'author': 'பரணதேவ நாயனார்',
        'author_tamil': 'பரணதேவ நாயனார்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321042,
        'position_in_collection': 42,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_24': {
        'work_name': 'சிவபெருமான் திருமும்மணிக்கோவை',
        'work_name_tamil': 'சிவபெருமான் திருமும்மணிக்கோவை',
        'author': 'இளம் பெருமாள் அடிகள்',
        'author_tamil': 'இளம் பெருமாள் அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321043,
        'position_in_collection': 43,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_25': {
        'work_name': 'மூத்தபிள்ளையார் திருமும்மணிக்கோவை',
        'work_name_tamil': 'மூத்தபிள்ளையார் திருமும்மணிக்கோவை',
        'author': 'அதிரா அடிகள்',
        'author_tamil': 'அதிரா அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321044,
        'position_in_collection': 44,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_26': {
        'work_name': 'கோயில் நான்மணிமாலை',
        'work_name_tamil': 'கோயில் நான்மணிமாலை',
        'author': 'பட்டினத்து அடிகள்',
        'author_tamil': 'பட்டினத்து அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321045,
        'position_in_collection': 45,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_27': {
        'work_name': 'திருக்கழுமல மும்மணிக்கோவை',
        'work_name_tamil': 'திருக்கழுமல மும்மணிக்கோவை',
        'author': 'பட்டினத்து அடிகள்',
        'author_tamil': 'பட்டினத்து அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321046,
        'position_in_collection': 46,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_28': {
        'work_name': 'திருவிடைமருதூர் மும்மணிக்கோவை',
        'work_name_tamil': 'திருவிடைமருதூர் மும்மணிக்கோவை',
        'author': 'பட்டினத்து அடிகள்',
        'author_tamil': 'பட்டினத்து அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321047,
        'position_in_collection': 47,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_29': {
        'work_name': 'திருவேகம்பமுடையார் திருவந்தாதி',
        'work_name_tamil': 'திருவேகம்பமுடையார் திருவந்தாதி',
        'author': 'பட்டினத்து அடிகள்',
        'author_tamil': 'பட்டினத்து அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321048,
        'position_in_collection': 48,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_30': {
        'work_name': 'திருவொற்றியூர் ஒருபா ஒருபஃது',
        'work_name_tamil': 'திருவொற்றியூர் ஒருபா ஒருபஃது',
        'author': 'பட்டினத்து அடிகள்',
        'author_tamil': 'பட்டினத்து அடிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321049,
        'position_in_collection': 49,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_31': {
        'work_name': 'திருநாரையூர் விநாயகர் இரட்டைமணிமாலை',
        'work_name_tamil': 'திருநாரையூர் விநாயகர் இரட்டைமணிமாலை',
        'author': 'நம்பியாண்டார் நம்பிகள்',
        'author_tamil': 'நம்பியாண்டார் நம்பிகள்',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321050,
        'position_in_collection': 50,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_32': {
        'work_name': 'கோயில் திருப்பண்ணியர் விருத்தம்',
        'work_name_tamil': 'கோயில் திருப்பண்ணியர் விருத்தம்',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321051,
        'position_in_collection': 51,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_33': {
        'work_name': 'திருத்தொண்டர் திருவந்தாதி',
        'work_name_tamil': 'திருத்தொண்டர் திருவந்தாதி',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321052,
        'position_in_collection': 52,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_34': {
        'work_name': 'ஆளுடையபிள்ளையார் திருவந்தாதி',
        'work_name_tamil': 'ஆளுடையபிள்ளையார் திருவந்தாதி',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321053,
        'position_in_collection': 53,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_35': {
        'work_name': 'ஆளுடையபிள்ளையார் திருச்சண்பை விருத்தம்',
        'work_name_tamil': 'ஆளுடையபிள்ளையார் திருச்சண்பை விருத்தம்',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321054,
        'position_in_collection': 54,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_36': {
        'work_name': 'ஆளுடையபிள்ளையார் திருமும்மணிக்கோவை',
        'work_name_tamil': 'ஆளுடையபிள்ளையார் திருமும்மணிக்கோவை',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321055,
        'position_in_collection': 55,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_37': {
        'work_name': 'ஆளுடையபிள்ளையார் திருவுலாமாலை',
        'work_name_tamil': 'ஆளுடையபிள்ளையார் திருவுலாமாலை',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321056,
        'position_in_collection': 56,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_38': {
        'work_name': 'ஆளுடையபிள்ளையார் திருக்கலம்பகம்',
        'work_name_tamil': 'ஆளுடையபிள்ளையார் திருக்கலம்பகம்',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321057,
        'position_in_collection': 57,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_39': {
        'work_name': 'ஆளுடையபிள்ளையார் திருத்தொகை',
        'work_name_tamil': 'ஆளுடையபிள்ளையார் திருத்தொகை',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321058,
        'position_in_collection': 58,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'file11_40': {
        'work_name': 'திருநாவுக்கரசு தேவர் திருஎகாதசமாலை',
        'work_name_tamil': 'திருநாவுக்கரசு தேவர் திருஎகாதசமாலை',
        'author': 'நம்பியாண்டார் நம்பி',
        'author_tamil': 'நம்பியாண்டார் நம்பி',
        'chronology_start_year': 800,
        'chronology_end_year': 1100,
        'chronology_confidence': 'medium',
        'chronology_notes': 'Saiva Prabandha Malai collection, 8th-11th century CE',
        'canonical_order': 321059,
        'position_in_collection': 59,
        'file': '11.பதினொன்றாம் திருமுறை.txt',
        'subcollection_id': 32111
    },
    'periya_puranam': {
        'work_name': 'Periya Puranam',
        'work_name_tamil': 'பெரியபுராணம்',
        'author': 'Sekkizhar',
        'author_tamil': 'சேக்கிழார்',
        'chronology_start_year': 1100,
        'chronology_end_year': 1200,
        'chronology_confidence': 'high',
        'chronology_notes': 'Composed by Sekkizhar in 12th century CE',
        'canonical_order': 321060,
        'position_in_collection': 60,
        'file': '12.பன்னிரண்டாம் திருமுறை.txt',
        'subcollection_id': 32112
    }
}
